---
site_name: rachel's digital garden 🌿
site_description: My personal digital garden
site_author: Rachie
site_url: https://rachelombok.github.io/digital-garden
copyright: Copyright &copy; 2021 Rachel Ombok
nav:
  - introduction: index.md
  - projects: projects/projects.md
  - game development:
      - community resources: gamedevelopment/communityresources.md
      - visual novel: gamedevelopment/visualnovel.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
  font:
    text: Padauk
  favicon: img/logo.bmp
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: custom
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css
  - stylesheets/colors.scss

extra:
  
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rachelombok
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/therachelplan
    - icon: fontawesome/solid/paper-plane
      link: mailto:rachel.ombok@nyu.edu

repo_name: rachelombok/digital-garden
repo_url: https://github.com/rachelombok/digital-garden
edit_uri: ""